### ISSUE TITLE
Translation to Portuguese (Brazil)

### ISSUE THREAD

**Issue by zehrique** [iakmds/librecamera#11]
Hi,
I'd like to contribute to Libre Camera by translating it to PT_BR.

Thank you.

**Comment by iakmds** [comment]
Hi Henrique, 

Portuguese has been added – you can translate [this](https://github.com/iakmds/librecamera/blob/master/assets/l10n/app_pt.arb) file. I did try to add only Brazilian Portuguese, but because of some problems I have only added regular Portuguese for now. When regular Portuguese gets requested, I will separate the two – I hope this is okay for you. Thanks

**Comment by zehrique** [comment]
OK! No problem.
Thank you!
