### ISSUE TITLE
Wrong resolution of the picture

### ISSUE THREAD

**Issue by RestlessDevil** [iakmds/librecamera#46]
No matter whether I set MAX or 4k, it uses wrong resolution in landscape (screenshots). I have two back cameras, so I suggest you should check which one snaps the picture.
![Screenshot_20221129-170403_Libre_Camera](https://user-images.githubusercontent.com/76730510/204581525-bf9d20b3-e9f6-4f0e-b00e-88b0b7538b16.png)
![Screenshot_20221129-170426_Gallery](https://user-images.githubusercontent.com/76730510/204582013-41ecd67b-b7eb-437e-afb9-d55fe31008ca.png)

**Comment by iakmds** [comment]
Hi, thanks for the issue.

You are right, sorry for this. Sadly the resolutions available in the Flutter camera this app is using are quite limited for now. Others have also created an issue in, #21 (the first one that is still kept open), #39, and #41. There is also an [issue in the Flutter](https://github.com/flutter/flutter/issues/45665) repository. 

Because of that I will close this issue as a duplicate, but thank you and do know that this request is one of the important features that are to be implemented once it's possible.
