### ISSUE TITLE
Weird resolution on ASUS Zenfone 8

### ISSUE THREAD

**Issue by starsforeveryone** [iakmds/librecamera#48]
Dear developers,

on my ASUS Zenfone 8 (latest LineageOS installed), when taking a picture, the resolution of my main camera is reduced to 3413 x 1920 px (6.6 MP, aspect ratio 16:9).

The sensor on my phone (Sony IMX686) is definitely 64 MP 4:3 or 16 MP 4:3 with quad bayering, so we're not using the full potential of the sensor.

The Android open source stock camera app takes pictures in 16 MP 4:3, which look really good thanks to the quad bayering. Resolution there is 4576 x 3432 px.

The front camera is a Sony IMX363 12 MP sensor. Resolution is again reduced to 3413 x 1920 px (6.6 MP, 16:9). With stock, it's 4032 x 3024 px (12 MP, 4:3).

A bugfix would be greatly appreciated! Thanks!

**Comment by iakmds** [comment]
Hi there, thanks for the issue.

You are right, sorry for this. Sadly the resolutions available in the Flutter camera this app is using are quite limited for now. Others have also created an issue in, #21 (the first one that is still kept open), #39, #41 and #46. Here is the [issue](https://github.com/flutter/flutter/issues/45665) in the Flutter repository.

Because of that I will close this issue as a duplicate, but thank you and do know that this request is one of the important features that are to be implemented once it's possible.
