### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by maverick74** [iakmds/librecamera#54]
I've been using OpenCamera until a few days ago and i would like to understand some differences.

1. In opencamera it's mentioned that the png format is not a "real" lossless png. Instead the app saves the photo in jpg and then coverts it to png. Is this also the case in LibreCamera?

2. One of the features mentioned in LibreCamera is a small size. Yet it takes ~20MB as opposed to just 4MB in opencamera. Why this difference?

Thank you

**Comment by iakmds** [comment]
Hi there,
1. Yes, this is also the case.
2. That is a good question. There is no proper answer I can give right now as there isn't anything special in regards to Libre Camera as a Flutter app to my knowledge. What I will do is try some things to minimize the size like analyzing app with the Flutter DevTools. Also, as seen in the [first release](https://github.com/iakmds/librecamera/releases/tag/v1.0.0) of Libre Camera, I could split up and upload the apk in future releases with 3 architectures, so that each architecture is only at about 7mb. This is because the full apk contains these 3 architectures inside, resulting in a larger apk size.

I hope your questions got answered. Let me know if you have more questions or if I can close this issue.

**Comment by maverick74** [comment]
1. :( that's sad....... i really like png!
2.  Wwell, i think it would be a good option because if a user checks the file size it will put LibreCamera in a big **disadvantage** (but then again... extra input from other users should be considered)

As for this issue, you can close it :)

Thank you **A LOT** for your time in clarifying me :)
